title: Makoto Nishikawa
email: nishikam@lawrence.edu
description: "Portfolio for Senior seminar"
baseurl: ""
url: "https://mako-lawrence.github.io" 
theme: minima
plugins:
  - jekyll-feed
  - jekyll-theme-minima
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
