title: Task Management App
email: nishikam@lawrence.edu
description: "Portfolio for Senior seminar"
baseurl: "https://mako-lawrence.github.io"
url: "" 
theme: minima
plugins:
  - jekyll-feed
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/